version: '3.8'

services:
  neo4j:
    image: neo4j:enterprise
    container_name: neo4j_enterprise
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP access for Neo4j Browser
      - "7687:7687"  # Bolt protocol for client connections
    environment:
      # Set the Neo4j authentication (update the password with a secure value)
      NEO4J_AUTH: "neo4j/admin"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: eval
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
