version: '3.8'

services:
  neo4j:
    image: neo4j:enterprise # pulls "latest" once, needs manual update for new versions
    container_name: neo4j_enterprise
    pull_policy: always
    restart: unless-stopped
    
    ports:
      - "7474:7474"  # HTTP access for Neo4j Browser
      - "7687:7687"  # Bolt protocol for client connections

    environment:
      # ---base---
      NEO4j_server_config_strict__validation_enabled: "false"

      # Set the Neo4j authentication (update the password with a secure value)
      NEO4J_AUTH: "neo4j/neo4j_enterprise!"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: eval
      # NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      
      # --- plugins you need ---
      NEO4J_PLUGINS: '["bloom", "apoc", "graph-data-science"]' 
    
      # --- expose GDS & Bloom procedures ---
      NEO4J_dbms_security_procedures_unrestricted: "gds.*,apoc.*,bloom.*"
      NEO4J_dbms_security_procedures_allowlist: "gds.*,apoc.*,bloom.*"
    

      # --- license paths (files are mounted at /licenses) ---
      # NEO4J_dbms_license__file: "/licenses/neo4j-enterprise.lic"
      NEO4J_gds.enterprise.license_file: "/licenses/neo4j-gds.lic"
      NEO4J_dbms_bloom_license__file: "/licenses/neo4j-bloom-server.lic"
      # --- license files ---

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - ./neo4j/gds:/var/lib/neo4j/gds
      - /opt/neo4j/licenses:/licenses:ro  # Mount licenses directory

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
